alias l='ls -alh'
# alias be='bundle exec'
alias gpr='git pull --rebase'
alias gnp='git --no-pager'
alias l2d1='logtodayone.rb'

alias recuke='cucumber --profile=rerun'
alias precuke='rm rerun.txt; cucumber --profile=rerun'

# Override heroku alias generated by 'bundler' plugin
unalias heroku

